/**
 * Grudge Fishing — standalone 3D fishing game
 * Grudge Studio Forge · Three.js + Cloudflare D1/R2
 * v2: Grudge6 characters with leather armor + bone-attached rod + FBM terrain
 */
import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
const API='https://grudge-fishing-api.grudge.workers.dev',R2='https://assets.grudge-studio.com/models/fishing',CHAR_BASE='https://assets.grudge-studio.com/models/characters';
const CHARACTERS=[{id:'human',name:'Human',emoji:'⚔️',color:'#c0a050'},{id:'barbarian',name:'Barbarian',emoji:'🪓',color:'#cc4444'},{id:'elf',name:'Elf',emoji:'🏹',color:'#44cc66'},{id:'dwarf',name:'Dwarf',emoji:'⛏️',color:'#aa8844'},{id:'orc',name:'Orc',emoji:'💀',color:'#669944'},{id:'undead',name:'Undead',emoji:'👻',color:'#8866aa'}];
const RODS=[{id:1,name:'Driftwood',tier:'T1',emoji:'🪵'},{id:2,name:'Bamboo',tier:'T2',emoji:'🎋'},{id:3,name:'Iron',tier:'T3',emoji:'⚙️'},{id:4,name:'Mithril',tier:'T4',emoji:'💎'},{id:5,name:'Leviathan',tier:'T5',emoji:'🐉'}];
const RACE_PREFIX={human:'WK_',barbarian:'BRB_',elf:'ELF_',dwarf:'DWF_',orc:'ORC_',undead:'UD_'};
const LEATHER_EQUIP={body:'B',arms:'B',legs:'B',head:'A'};
const SLOT_PATTERNS=[{slot:'body',re:/Units_Body_([A-Z])/i},{slot:'arms',re:/Units_Arms_([A-Z])/i},{slot:'legs',re:/Units_Legs_([A-Z])/i},{slot:'head',re:/Units_head_([A-Z])/i},{slot:'shoulders',re:/Units_shoulderpads_([A-Z])/i}];
const ROD_BONE_NAMES=['R_hand_container','RightHand','R_hand','R_Hand','mixamorig:RightHand','Bip01_R_Hand'];
const WV=`varying vec2 vUv;varying vec3 vWorldPos;uniform float uTime;void main(){vUv=uv;vec3 pos=position;pos.y+=sin(pos.x*0.8+uTime*0.7)*0.15+sin(pos.z*0.6+uTime*0.5)*0.12+cos(pos.x*0.3+pos.z*0.5+uTime*0.3)*0.08;vWorldPos=(modelMatrix*vec4(pos,1.0)).xyz;gl_Position=projectionMatrix*modelViewMatrix*vec4(pos,1.0);}`;
const WF=`precision highp float;varying vec2 vUv;varying vec3 vWorldPos;uniform float uTime;uniform vec3 uDeepColor;uniform vec3 uShallowColor;uniform vec3 uFoamColor;#define TAU 6.28318530718\nvec3 caustic(vec2 uv){vec2 p=mod(uv*TAU,TAU)-250.0;float time=uTime*0.4+23.0;vec2 i=vec2(p);float c=1.0;float inten=0.005;for(int n=0;n<4;n++){float t=time*(1.0-(3.5/float(n+1)));i=p+vec2(cos(t-i.x)+sin(t+i.y),sin(t-i.y)+cos(t+i.x));c+=1.0/length(vec2(p.x/(sin(i.x+t)/inten),p.y/(cos(i.y+t)/inten)));}c/=4.0;c=1.17-pow(c,1.4);vec3 color=vec3(pow(abs(c),8.0));return clamp(color+vec3(0.0,0.35,0.5),0.0,1.0);}void main(){vec2 wUv=vWorldPos.xz*0.05;vec3 caust=caustic(wUv*1.5+uTime*0.02);float depth=smoothstep(-2.0,8.0,length(vWorldPos.xz));vec3 wc=mix(uShallowColor,uDeepColor,depth);float foam=smoothstep(0.4,0.0,depth)*0.3;wc=mix(wc,uFoamColor,foam);wc+=caust*0.12;gl_FragColor=vec4(wc,mix(0.7,0.9,depth));}`;
function fbmNoise(x,z,seed=42){let h=0,amp=1,freq=0.08;for(let i=0;i<5;i++){h+=amp*Math.sin((x+seed)*freq+Math.cos(z*freq*1.3))*Math.cos((z+seed*0.7)*freq+Math.sin(x*freq*0.9));amp*=0.5;freq*=2.1;seed+=13.37;}return h;}
function seededRandom(seed){let s=seed;return()=>{s=(s*16807)%2147483647;return(s-1)/2147483646;};}
let scene,camera,renderer,controls,clock,mixer=null,characterModel=null,rodModel=null,rodBone=null,selectedRod=1,selectedChar='human';
const gltfLoader=new GLTFLoader();let fishingState='idle',castResult=null,biteTimer=0,reelWindowTimer=0,tension=0.5,tensionSpeed=0,reelProgress=0,bobberTime=0;
let totalCatches=0,totalXp=0,totalGold=0;let bobber=null,bobberTarget=new THREE.Vector3(),fishingLine=null,fishingLineGeom=null,waterMat=null,swimFish=[],splashParticles=null,splashLife=0;
const IR=18;
function getTerrainY(x,z){const d=Math.sqrt(x*x+z*z);if(d>IR)return-0.3;return Math.max(-0.2,Math.pow(Math.max(0,1-d/IR),1.5)*(1.8+fbmNoise(x,z,42)*1.2));}
function initScene(){const cv=document.getElementById('game-canvas');clock=new THREE.Clock();scene=new THREE.Scene();scene.background=new THREE.Color(0x87ceeb);scene.fog=new THREE.FogExp2(0x87ceeb,0.008);camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,0.1,500);camera.position.set(3,4,8);renderer=new THREE.WebGLRenderer({canvas:cv,antialias:true});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.4;controls=new OrbitControls(camera,cv);controls.target.set(0,1,0);controls.enableDamping=true;controls.dampingFactor=0.08;controls.maxPolarAngle=Math.PI*0.48;controls.minDistance=3;controls.maxDistance=30;controls.update();scene.add(new THREE.HemisphereLight(0x87ceeb,0x2d5a27,0.6));const sun=new THREE.DirectionalLight(0xfff4e0,2.0);sun.position.set(20,30,15);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.near=1;sun.shadow.camera.far=80;[-20,20,-20,20].forEach((v,i)=>{const c=sun.shadow.camera;[c.left,c.right,c.top,c.bottom][i]=v;});scene.add(sun);const fl=new THREE.DirectionalLight(0x8ec8f0,0.4);fl.position.set(-10,15,-10);scene.add(fl);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});}
function createIsland(){const geo=new THREE.PlaneGeometry(IR*2,IR*2,96,96),pos=geo.attributes.position,colors=new Float32Array(pos.count*3);const sc=new THREE.Color(0xd4a84b),gc=new THREE.Color(0x4a7c3f),dc=new THREE.Color(0x8B6914),rc=new THREE.Color(0x777777);for(let i=0;i<pos.count;i++){const x=pos.getX(i),z=pos.getY(i),h=getTerrainY(x,z);pos.setZ(i,h);let c;if(h<0.1)c=sc;else if(h<0.6)c=sc.clone().lerp(gc,(h-0.1)/0.5);else if(h<1.5)c=gc.clone().lerp(dc,(h-0.6)/0.9);else c=dc.clone().lerp(rc,Math.min(1,(h-1.5)));colors[i*3]=c.r;colors[i*3+1]=c.g;colors[i*3+2]=c.b;}geo.setAttribute('color',new THREE.BufferAttribute(colors,3));geo.computeVertexNormals();const m=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({vertexColors:true,roughness:0.92}));m.rotation.x=-Math.PI/2;m.position.y=-0.15;m.receiveShadow=true;m.castShadow=true;scene.add(m);const rng=seededRandom(777);for(let i=0;i<18;i++){const a=rng()*Math.PI*2,d=3+rng()*(IR-5),tx=Math.cos(a)*d,tz=Math.sin(a)*d,ty=getTerrainY(tx,tz);if(ty>0.2&&ty<2.5)createPalmTree(tx,tz,ty-0.15);}for(let i=0;i<12;i++){const a=rng()*Math.PI*2,d=4+rng()*(IR-4),rx=Math.cos(a)*d,rz=Math.sin(a)*d,ry=getTerrainY(rx,rz);if(ry<0)continue;const s=0.2+rng()*0.6;const r=new THREE.Mesh(new THREE.DodecahedronGeometry(s,1),new THREE.MeshStandardMaterial({color:0x5a5a5a+Math.floor(rng()*0x222222),roughness:0.88,flatShading:true}));r.position.set(rx,ry-0.15+s*0.3,rz);r.rotation.set(rng()*3,rng()*3,rng()*3);r.scale.set(1,0.5+rng()*0.5,1);r.castShadow=true;r.receiveShadow=true;scene.add(r);}for(let i=0;i<25;i++){const a=rng()*Math.PI*2,d=2+rng()*(IR-4),bx=Math.cos(a)*d,bz=Math.sin(a)*d,by=getTerrainY(bx,bz);if(by<0.3||by>2.0)continue;const s=0.15+rng()*0.3;const g2=new THREE.SphereGeometry(s,6,5);const p2=g2.attributes.position;for(let j=0;j<p2.count;j++){p2.setY(j,p2.getY(j)*0.6+rng()*0.05);p2.setX(j,p2.getX(j)+rng()*0.03);}g2.computeVertexNormals();const bush=new THREE.Mesh(g2,new THREE.MeshStandardMaterial({color:0x2d6a2d+Math.floor(rng()*0x3300),roughness:0.85}));bush.position.set(bx,by-0.15+s*0.4,bz);bush.castShadow=true;scene.add(bush);}}
function createPalmTree(x,z,by=0){const g=new THREE.Group(),h=2.5+Math.random()*1.5;const t=new THREE.Mesh(new THREE.CylinderGeometry(0.06,0.1,h,8),new THREE.MeshStandardMaterial({color:0x8B6914,roughness:0.9}));t.position.y=h/2;t.rotation.z=Math.sin(x*0.5)*0.12;t.rotation.x=Math.cos(z*0.3)*0.08;t.castShadow=true;g.add(t);const fc=5+Math.floor(Math.random()*4);for(let i=0;i<fc;i++){const l=1.5+Math.random();const fg=new THREE.PlaneGeometry(l,0.3+Math.random()*0.2,8,1);const fp=fg.attributes.position;for(let j=0;j<fp.count;j++)fp.setZ(j,-Math.abs(fp.getX(j))*(0.3+Math.random()*0.3));fg.computeVertexNormals();const f=new THREE.Mesh(fg,new THREE.MeshStandardMaterial({color:0x1d6a1d+Math.floor(Math.random()*0x2200),side:THREE.DoubleSide,roughness:0.75}));f.position.y=h;f.rotation.y=(i/fc)*Math.PI*2+Math.random()*0.2;f.rotation.x=0.4+Math.random()*0.4;f.castShadow=true;g.add(f);}g.position.set(x,by,z);scene.add(g);}
function createWater(){waterMat=new THREE.ShaderMaterial({vertexShader:WV,fragmentShader:WF,uniforms:{uTime:{value:0},uDeepColor:{value:new THREE.Color(0x0a3d5c)},uShallowColor:{value:new THREE.Color(0x1a8a9a)},uFoamColor:{value:new THREE.Color(0xc8e6f0)}},transparent:true,side:THREE.DoubleSide});const w=new THREE.Mesh(new THREE.PlaneGeometry(200,200,128,128),waterMat);w.rotation.x=-Math.PI/2;w.position.y=-0.3;w.receiveShadow=true;scene.add(w);}
async function createDock(){try{const gltf=await gltfLoader.loadAsync(`${R2}/environment/Dock_Long.glb`);const d=gltf.scene;d.scale.setScalar(0.012);d.position.set(0,0.05,-5);d.rotation.y=Math.PI;d.traverse(c=>{if(c.isMesh){c.castShadow=true;c.receiveShadow=true;}});scene.add(d);}catch{const pm=new THREE.MeshStandardMaterial({color:0x8B6914,roughness:0.85});const p=new THREE.Mesh(new THREE.BoxGeometry(2,0.1,6),pm);p.position.set(0,0.2,-5);p.castShadow=true;p.receiveShadow=true;scene.add(p);}}
function createBobber(){const g=new THREE.Group();g.add(new THREE.Mesh(new THREE.SphereGeometry(0.06,12,12),new THREE.MeshStandardMaterial({color:0xff3333})));const b=new THREE.Mesh(new THREE.SphereGeometry(0.05,12,12),new THREE.MeshStandardMaterial({color:0xffffff}));b.position.y=-0.04;g.add(b);g.visible=false;scene.add(g);bobber=g;fishingLineGeom=new THREE.BufferGeometry();fishingLineGeom.setAttribute('position',new THREE.BufferAttribute(new Float32Array(90),3));fishingLine=new THREE.Line(fishingLineGeom,new THREE.LineBasicMaterial({color:0x888888,transparent:true,opacity:0.6}));fishingLine.visible=false;fishingLine.frustumCulled=false;scene.add(fishingLine);const pG=new THREE.BufferGeometry();pG.setAttribute('position',new THREE.BufferAttribute(new Float32Array(75),3));pG.setAttribute('velocity',new THREE.BufferAttribute(new Float32Array(75),3));splashParticles=new THREE.Points(pG,new THREE.PointsMaterial({color:0xaaddff,size:0.04,transparent:true,opacity:0.8}));splashParticles.visible=false;scene.add(splashParticles);}
function findBone(m,names){let f=null;m.traverse(c=>{if(f)return;if(c.isSkinnedMesh&&c.skeleton)for(const n of names){const b=c.skeleton.bones.find(b=>b.name===n);if(b){f=b;return;}}});if(f)return f;m.traverse(c=>{if(f)return;for(const n of names)if(c.name===n||c.name.toLowerCase().includes(n.toLowerCase())){f=c;return;}});return f;}
function equipLeatherArmor(m,pfx){m.traverse(c=>{if(!c.isMesh&&!c.isSkinnedMesh)return;const s=c.name.startsWith(pfx)?c.name.slice(pfx.length):c.name;for(const{slot,re}of SLOT_PATTERNS){const match=s.match(re);if(match){c.visible=LEATHER_EQUIP[slot]?(match[1]||'A').toUpperCase()===LEATHER_EQUIP[slot]:false;break;}}if(/sword|axe|hammer|pick|spear|bow|staff|shield|bag|wood|quiver/i.test(s))c.visible=false;});}
async function loadCharacter(id){setLoadText(`Loading ${id}...`);if(characterModel){scene.remove(characterModel);mixer=null;rodBone=null;if(rodModel){rodModel.parent?.remove(rodModel);rodModel=null;}}try{const gltf=await gltfLoader.loadAsync(`${CHAR_BASE}/${id}.glb`);characterModel=gltf.scene;characterModel.scale.setScalar(0.01);characterModel.position.set(0,0.15,-3);characterModel.rotation.y=Math.PI;characterModel.traverse(c=>{if(c.isMesh||c.isSkinnedMesh){c.castShadow=true;c.receiveShadow=true;}});equipLeatherArmor(characterModel,RACE_PREFIX[id]||'WK_');scene.add(characterModel);if(gltf.animations.length>0){mixer=new THREE.AnimationMixer(characterModel);mixer.clipAction(gltf.animations[0]).play();}rodBone=findBone(characterModel,ROD_BONE_NAMES);if(rodBone)await attachRod();}catch(e){console.warn('Char load fail:',e.message);characterModel=null;}}
async function attachRod(){if(!rodBone)return;if(rodModel){rodModel.parent?.remove(rodModel);rodModel=null;}try{const g=await gltfLoader.loadAsync(`${R2}/rods/FishingRod_Lvl${selectedRod}.glb`);rodModel=g.scene;rodModel.position.set(0,5,2);rodModel.rotation.set(-Math.PI*0.15,0,Math.PI*0.5);rodBone.add(rodModel);}catch{rodModel=new THREE.Mesh(new THREE.CylinderGeometry(0.5,0.3,80,8),new THREE.MeshStandardMaterial({color:0x8B6914}));rodModel.position.set(0,5,2);rodModel.rotation.set(-Math.PI*0.15,0,Math.PI*0.5);rodBone.add(rodModel);}}
async function spawnAmbientFish(){try{const[cr,ur]=await Promise.all([fetch(`${API}/api/fishing/species?rarity=common`),fetch(`${API}/api/fishing/species?rarity=uncommon`)]);const common=await cr.json(),uncommon=await ur.json();const toSpawn=[...common.sort(()=>Math.random()-0.5).slice(0,8),...uncommon.sort(()=>Math.random()-0.5).slice(0,4)];for(const fish of toSpawn){try{const g=await gltfLoader.loadAsync(fish.model_url);const m=g.scene;m.scale.setScalar(fish.rarity==='uncommon'?0.010:0.007+Math.random()*0.004);const a=Math.random()*Math.PI*2,d=8+Math.random()*15,x=Math.cos(a)*d,z=Math.sin(a)*d,y=-0.6-Math.random()*2;m.position.set(x,y,z);m.rotation.y=Math.random()*Math.PI*2;m.traverse(c=>{if(c.isMesh)c.castShadow=false;});scene.add(m);swimFish.push({model:m,speed:0.2+Math.random()*0.6,phase:Math.random()*Math.PI*2,baseX:x,baseY:y,baseZ:z,swimRadius:2+Math.random()*4,dir:Math.random()>0.5?1:-1});}catch{}}}catch(e){console.warn('Fish spawn fail:',e.message);}}
async function apiCast(){try{return await(await fetch(`${API}/api/fishing/cast`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({player_id:'guest',rod_id:selectedRod,player_level:1+Math.floor(totalCatches/5),biome:'coastal'})})).json();}catch{return null;}}
async function apiCatch(fid,w){try{return await(await fetch(`${API}/api/fishing/catch`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({player_id:'guest',fish_species_id:fid,rod_id:selectedRod,weight:w})})).json();}catch{return null;}}
async function castLine(){if(fishingState!=='idle')return;setState('casting');castResult=await apiCast();bobberTarget.set((Math.random()-0.5)*2,-0.3,-8-Math.random()*4);bobber.position.set(0,2,-3);bobber.visible=true;fishingLine.visible=true;setTimeout(()=>{bobber.position.copy(bobberTarget);triggerSplash(bobberTarget);setState('waiting');biteTimer=castResult?castResult.bite_delay_ms/1000:5+Math.random()*8;},800);}
function startReel(){if(fishingState!=='bite')return;setState('reeling');tension=0.5;tensionSpeed=0;reelProgress=0;}
function pumpReel(){if(fishingState!=='reeling')return;tensionSpeed+=0.15;reelProgress+=0.02/(castResult?.difficulty||0.5);}
function cancelFishing(){if(fishingState==='idle')return;bobber.visible=false;fishingLine.visible=false;setState('idle');}
async function fishCaught(){setState('catching');bobber.visible=false;fishingLine.visible=false;totalCatches++;let cr=null;if(castResult){cr=await apiCatch(castResult.fish_species_id,castResult.weight);totalXp+=castResult.base_xp;totalGold+=castResult.base_gold;}showCatchPopup(castResult,cr);updateHudStats();setTimeout(()=>setState('idle'),2500);}
function fishEscaped(){setState('failed');bobber.visible=false;fishingLine.visible=false;setTimeout(()=>setState('idle'),1500);}
function setState(s){fishingState=s;document.getElementById('state-badge').textContent={idle:'READY',casting:'CASTING...',waiting:'WAITING FOR BITE...',bite:'🐟 FISH ON! REEL!',reeling:'REELING...',catching:'🎉 CAUGHT!',failed:'💨 GOT AWAY!'}[s]||s;document.getElementById('btn-cast').disabled=s!=='idle';document.getElementById('btn-reel').disabled=s!=='bite'&&s!=='reeling';document.getElementById('tension-panel').classList.toggle('visible',s==='reeling');}
function updateHudStats(){document.getElementById('stat-catches').textContent=totalCatches;document.getElementById('stat-xp').textContent=totalXp;document.getElementById('stat-gold').textContent=totalGold;}
function showCatchPopup(c,cr){if(!c)return;document.getElementById('catch-name').textContent=c.fish_name;document.getElementById('catch-weight').textContent=`${c.weight} lbs`;const re=document.getElementById('catch-rarity');re.textContent=c.rarity;re.className=`catch-rarity rarity-${c.rarity}`;document.getElementById('catch-xp').textContent=`+${c.base_xp} XP • +${c.base_gold} Gold`;document.getElementById('catch-record').style.display=cr?.is_personal_record?'':'none';const p=document.getElementById('catch-popup');p.classList.add('show');setTimeout(()=>p.classList.remove('show'),2500);}
function setLoadText(t){const e=document.getElementById('load-text');if(e)e.textContent=t;}
function updateLine(){if(!fishingLine.visible)return;const rt=new THREE.Vector3(0,2.5,-3),bp=bobber.position,p=fishingLineGeom.attributes.position.array;for(let i=0;i<30;i++){const t=i/29;p[i*3]=THREE.MathUtils.lerp(rt.x,bp.x,t);p[i*3+2]=THREE.MathUtils.lerp(rt.z,bp.z,t);p[i*3+1]=THREE.MathUtils.lerp(rt.y,bp.y,t)-Math.sin(t*Math.PI)*0.4*(1-t*0.5);}fishingLineGeom.attributes.position.needsUpdate=true;}
function triggerSplash(pos){const p=splashParticles.geometry.attributes.position.array,v=splashParticles.geometry.attributes.velocity.array;for(let i=0;i<p.length/3;i++){p[i*3]=pos.x+(Math.random()-.5)*.15;p[i*3+1]=pos.y;p[i*3+2]=pos.z+(Math.random()-.5)*.15;v[i*3]=(Math.random()-.5)*2;v[i*3+1]=1.5+Math.random()*2.5;v[i*3+2]=(Math.random()-.5)*2;}splashParticles.geometry.attributes.position.needsUpdate=true;splashParticles.visible=true;splashLife=0.8;}
function updateSplash(dt){splashLife-=dt;if(splashLife<=0){splashParticles.visible=false;return;}const p=splashParticles.geometry.attributes.position.array,v=splashParticles.geometry.attributes.velocity.array;for(let i=0;i<p.length/3;i++){p[i*3]+=v[i*3]*dt;p[i*3+1]+=v[i*3+1]*dt;p[i*3+2]+=v[i*3+2]*dt;v[i*3+1]-=9.8*dt;}splashParticles.geometry.attributes.position.needsUpdate=true;splashParticles.material.opacity=splashLife;}
function animate(){requestAnimationFrame(animate);const dt=clock.getDelta();bobberTime+=dt;controls.update();if(mixer)mixer.update(dt);if(waterMat)waterMat.uniforms.uTime.value+=dt;for(const f of swimFish){f.phase+=dt*f.speed;const r=f.swimRadius||3;f.model.position.x=f.baseX+Math.sin(f.phase)*r*f.dir;f.model.position.z=(f.baseZ||0)+Math.cos(f.phase*0.7)*r*0.6;f.model.position.y=f.baseY+Math.sin(f.phase*2)*0.1;f.model.rotation.y=Math.atan2(Math.cos(f.phase)*f.dir,-Math.sin(f.phase*0.7)*0.6);}
switch(fishingState){case'waiting':bobber.position.y=-0.3+Math.sin(bobberTime*2)*0.02;biteTimer-=dt;if(biteTimer<=0){setState('bite');reelWindowTimer=(castResult?.reel_window_ms||3000)/1000;triggerSplash(bobber.position);}break;case'bite':bobber.position.y=-0.3+Math.sin(bobberTime*12)*0.08-0.05;reelWindowTimer-=dt;if(reelWindowTimer<=0)fishEscaped();break;case'reeling':{const diff=castResult?.difficulty||0.5;tensionSpeed+=(((Math.sin(bobberTime*3.5)*0.5+Math.random()*0.3)*diff)-0.3)*dt*2;tensionSpeed*=0.95;tension=Math.max(0,Math.min(1,tension+tensionSpeed*dt));if(tension<=0.05||tension>=0.95){fishEscaped();break;}if(tension>0.3&&tension<0.7)reelProgress+=dt*0.15/diff;bobber.position.lerpVectors(bobberTarget,new THREE.Vector3(0,-0.3,-3),reelProgress);bobber.position.y=-0.3+Math.sin(bobberTime*6)*0.04;document.getElementById('tension-marker').style.left=`${tension*100}%`;document.getElementById('progress-fill').style.width=`${reelProgress*100}%`;if(reelProgress>=1.0)fishCaught();break;}}
updateLine();if(splashParticles.visible)updateSplash(dt);renderer.render(scene,camera);}
function buildRodPanel(){const p=document.getElementById('rod-panel');p.innerHTML=RODS.map(r=>`<button class="rod-btn ${r.id===selectedRod?'active':''}" data-rod="${r.id}" title="${r.name} (${r.tier})"><span class="rod-icon">${r.emoji}</span><span class="rod-tier">${r.tier}</span></button>`).join('');p.addEventListener('click',async e=>{const b=e.target.closest('.rod-btn');if(!b)return;selectedRod=parseInt(b.dataset.rod);p.querySelectorAll('.rod-btn').forEach(b=>b.classList.toggle('active',parseInt(b.dataset.rod)===selectedRod));if(rodBone)await attachRod();});}
function buildCharPanel(){const p=document.getElementById('char-panel');p.innerHTML=CHARACTERS.map(c=>`<button class="char-btn ${c.id===selectedChar?'active':''}" data-char="${c.id}" title="${c.name}" style="border-color:${c.color}">${c.emoji}</button>`).join('');p.addEventListener('click',async e=>{const b=e.target.closest('.char-btn');if(!b)return;selectedChar=b.dataset.char;p.querySelectorAll('.char-btn').forEach(b=>b.classList.toggle('active',b.dataset.char===selectedChar));await loadCharacter(selectedChar);});}
function setupControls(){document.getElementById('btn-cast').addEventListener('click',castLine);document.getElementById('btn-reel').addEventListener('click',()=>{if(fishingState==='bite')startReel();else if(fishingState==='reeling')pumpReel();});document.getElementById('btn-cancel').addEventListener('click',cancelFishing);addEventListener('click',()=>{if(fishingState==='reeling')pumpReel();});addEventListener('keydown',e=>{if(e.code==='KeyF')castLine();else if(e.code==='KeyR'){if(fishingState==='bite')startReel();else if(fishingState==='reeling')pumpReel();}else if(e.code==='Escape')cancelFishing();});}
async function boot(){initScene();setLoadText('Building island...');createIsland();setLoadText('Creating ocean...');createWater();setLoadText('Placing dock...');await createDock();createBobber();setLoadText('Spawning fish...');await spawnAmbientFish();setLoadText('Loading character...');await loadCharacter(selectedChar);buildRodPanel();buildCharPanel();setupControls();updateHudStats();setState('idle');document.getElementById('loading').classList.add('hidden');animate();}
boot();
